/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import micromips.processor.Execution;
import micromips.processor.InstructionDecode;
import micromips.processor.InstructionFetch;
import micromips.processor.MemoryAccess;
import micromips.processor.Scheduler;
import models.Storage;
import utilities.Errors;
import utilities.UtilityFunctions;

/**
 *
 * @author Roscoe Alicbusan
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    DialogClass dialogClass;
    private PipelinePanel pipelinePanel;

    public MainFrame() {
        dialogClass = new DialogClass(this);
        pipelinePanel = new PipelinePanel();
        pipelinePanel.setSize(452, 402);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        sourceCodeArea = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        internalRegTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        registerTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        memoryTable = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        codeTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane(pipelinePanel);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        loadButton = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MicroMIPS64");
        setMaximumSize(new java.awt.Dimension(945, 640));
        setMinimumSize(new java.awt.Dimension(945, 640));
        setSize(new java.awt.Dimension(945, 640));

        jLabel1.setText("Pipeline Map:");

        jLabel2.setText("Internal MIPS64 Registers:");

        jLabel17.setText("Registers:");

        sourceCodeArea.setColumns(20);
        sourceCodeArea.setRows(5);
        jScrollPane3.setViewportView(sourceCodeArea);

        jScrollPane4.setViewportView(jScrollPane3);

        jLabel26.setText("Source Code:");

        internalRegTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Register", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DefaultTableModel internalRegModel = (DefaultTableModel) internalRegTable.getModel();

        internalRegModel.addRow(new Object[]{"IF/ID.IR", "00000000"});
        internalRegModel.addRow(new Object[]{"IF/ID.NPC", "0000000000000000"});
        internalRegModel.addRow(new Object[]{"PC", "0000000000000000"});
        internalRegModel.addRow(new Object[]{"ID/EX.IR", "00000000"});
        internalRegModel.addRow(new Object[]{"ID/EX.NPC", "0000000000000000"});
        internalRegModel.addRow(new Object[]{"ID/EX.A", "0000000000000000"});
        internalRegModel.addRow(new Object[]{"ID/EX.B", "0000000000000000"});
        internalRegModel.addRow(new Object[]{"ID/EX.IMM", "0000000000000000"});
        internalRegModel.addRow(new Object[]{"EX/MEM.IR", "00000000"});
        internalRegModel.addRow(new Object[]{"EX/MEM.ALU", "0000000000000000"});
        internalRegModel.addRow(new Object[]{"EX/MEM.COND", "0"});
        internalRegModel.addRow(new Object[]{"EX/MEM.B", "0000000000000000"});
        internalRegModel.addRow(new Object[]{"MEM/WB.IR", "00000000"});
        internalRegModel.addRow(new Object[]{"MEM/WB.LMD", "0000000000000000"});
        internalRegModel.addRow(new Object[]{"MEM/WB.ALU", "0000000000000000"});
        internalRegTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(internalRegTable);
        if (internalRegTable.getColumnModel().getColumnCount() > 0) {
            internalRegTable.getColumnModel().getColumn(0).setResizable(false);
            internalRegTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            internalRegTable.getColumnModel().getColumn(1).setResizable(false);
            internalRegTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        registerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Register", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            JTextField textField = new JTextField("");

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DefaultTableModel registerModel = (DefaultTableModel) registerTable.getModel();

        for(int i=0;i<32;i++){
            registerModel.addRow(new Object[]{"R" + i, "0000000000000000"});
        }

        registerTable.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                JTable table =(JTable) me.getSource();
                Point p = me.getPoint();
                if (me.getClickCount() == 2) {
                    int row = table.rowAtPoint(p);
                    dialogClass.createDialog("NOINPUT", 0, row, 0);
                    dialogClass.showDialog();
                }
            }
        });
        registerTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(registerTable);

        jLabel3.setText("Data Segment:");

        memoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Address", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        memoryTable.setMaximumSize(new java.awt.Dimension(0, 0));
        memoryTable.setMinimumSize(new java.awt.Dimension(0, 0));
        memoryTable.getTableHeader().setReorderingAllowed(false);
        DefaultTableModel memoryModel = (DefaultTableModel) memoryTable.getModel();

        int memVal = 0x3000;

        for(int i=0;i<1024;i++){
            memoryModel.addRow(new Object[]{Integer.toHexString(memVal).toUpperCase(), "0000000000000000"});
            memVal += 0x8;
        }

        memoryTable.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                JTable table =(JTable) me.getSource();
                Point p = me.getPoint();
                String memoryAddress;
                if (me.getClickCount() == 2) {
                    int row = table.rowAtPoint(p);
                    memoryAddress = (memoryTable.getValueAt(row, 0)).toString();
                    dialogClass.createDialog(memoryAddress, 1, row, 0);
                    dialogClass.showDialog();
                }
            }
        });
        jScrollPane6.setViewportView(memoryTable);
        if (memoryTable.getColumnModel().getColumnCount() > 0) {
            memoryTable.getColumnModel().getColumn(0).setResizable(false);
            memoryTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            memoryTable.getColumnModel().getColumn(1).setResizable(false);
            memoryTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        codeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Address", "Representation", "Label", "Instruction"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        codeTable.getTableHeader().setReorderingAllowed(false);
        DefaultTableModel codeModel = (DefaultTableModel) codeTable.getModel();

        int codeVal = 0x1000;

        for(int i=0;i<2048;i++){
            codeModel.addRow(new Object[]{Integer.toHexString(codeVal).toUpperCase(), "00000000"});
            codeVal += 0x4;
        }
        jScrollPane7.setViewportView(codeTable);
        if (codeTable.getColumnModel().getColumnCount() > 0) {
            codeTable.getColumnModel().getColumn(0).setResizable(false);
            codeTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            codeTable.getColumnModel().getColumn(1).setResizable(false);
            codeTable.getColumnModel().getColumn(1).setPreferredWidth(60);
            codeTable.getColumnModel().getColumn(2).setResizable(false);
            codeTable.getColumnModel().getColumn(2).setPreferredWidth(30);
            codeTable.getColumnModel().getColumn(3).setResizable(false);
            codeTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        jLabel4.setText("Code Segment:");

        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 402));
        pipelinePanel.repaint();

        jMenu1.setText("Run");

        jMenu5.setText("Run One Cycle");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu5);

        jMenu6.setText("Run All Cycles");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        loadButton.setText("Load");
        loadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(loadButton);

        jMenu3.setText("Memory");

        jMenu4.setText("GOTO Memory");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu3.add(jMenu4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(220, 220, 220)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(204, 204, 204)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadButtonMouseClicked
        try {
            Errors.getParsingErrors().clear();
            Errors.getRuntimeErrors().clear();
            clearValues();
            updateTables();
            String userCode = sourceCodeArea.getText();

            //load into memory
            Scheduler.getInstance().setInput(userCode);
            Scheduler.getInstance().applyModifications();
            Scheduler.getInstance().setOpcodes();
            Scheduler.getInstance().storeOpcodes();

            ArrayList<String> codeList = Scheduler.getInstance().getCodeList();
            ArrayList<Integer> list = Scheduler.getInstance().getOpcodes();
            System.out.println("List size: " + list.size());
            for (int i = 0; i < list.size(); i++) {
                codeTable.setValueAt(UtilityFunctions.to32BitHexString(list.get(i)), i, 1);
                codeTable.setValueAt(codeList.get(i), i, 3);
            }

        } catch (Exception e) {
            //do nothing
        }
    }//GEN-LAST:event_loadButtonMouseClicked

    public void clearValues() {
        for (int i = 0; i < 1023; i++) {
            int mem = 0x3000 + (i * 0x8);
            Storage.dataStoreDouble(mem, 0x0);
        }
        for (int i = 1; i < 32; i++) {
            Storage.storeRegisterValue(i, 0x0);
        }
        InstructionFetch.PC = 0x1000;

        Execution.EX_MEM_COND = false;

        InstructionFetch.IF_ID_IR = InstructionFetch.IF_ID_NPC
                = InstructionDecode.ID_EX_IR = InstructionDecode.ID_EX_NPC
                = Execution.EX_MEM_IR = MemoryAccess.MEM_WB_IR = 0x0;

        InstructionDecode.ID_EX_A = InstructionDecode.ID_EX_B
                = InstructionDecode.ID_EX_IMM = Execution.EX_MEM_ALU_OUTPUT
                = Execution.EX_MEM_B = MemoryAccess.MEM_WB_ALU_OUTPUT = MemoryAccess.MEM_WB_LMD = 0x0;
    }

    public void updateTables() {
        for (int i = 0; i < 1023; i++) {
            int mem = 0x3000 + (i * 0x8);
            memoryTable.setValueAt(UtilityFunctions.to64BitHexString(Storage.dataLoadDouble(mem)), i, 1);
        }
        for (int i = 1; i < 32; i++) {
            registerTable.setValueAt(UtilityFunctions.to64BitHexString(Storage.getRegisterValue(i)), i, 1);
        }

        internalRegTable.setValueAt(UtilityFunctions.to32BitHexString(InstructionFetch.IF_ID_IR), 0, 1);
        internalRegTable.setValueAt(UtilityFunctions.to64BitHexString(InstructionFetch.IF_ID_NPC), 1, 1);
        internalRegTable.setValueAt(UtilityFunctions.to64BitHexString(InstructionFetch.PC), 2, 1);
        internalRegTable.setValueAt(UtilityFunctions.to32BitHexString(InstructionDecode.ID_EX_IR), 3, 1);
        internalRegTable.setValueAt(UtilityFunctions.to64BitHexString(InstructionDecode.ID_EX_NPC), 4, 1);
        internalRegTable.setValueAt(UtilityFunctions.to64BitHexString(InstructionDecode.ID_EX_A), 5, 1);
        internalRegTable.setValueAt(UtilityFunctions.to64BitHexString(InstructionDecode.ID_EX_B), 6, 1);
        internalRegTable.setValueAt(UtilityFunctions.to64BitHexString(InstructionDecode.ID_EX_IMM), 7, 1);
        internalRegTable.setValueAt(UtilityFunctions.to32BitHexString(Execution.EX_MEM_IR), 8, 1);
        internalRegTable.setValueAt(UtilityFunctions.to64BitHexString(Execution.EX_MEM_ALU_OUTPUT), 9, 1);
        internalRegTable.setValueAt(Execution.EX_MEM_COND ? 1 : 0, 10, 1);
        internalRegTable.setValueAt(UtilityFunctions.to64BitHexString(Execution.EX_MEM_B), 11, 1);
        internalRegTable.setValueAt(UtilityFunctions.to32BitHexString(MemoryAccess.MEM_WB_IR), 12, 1);
        internalRegTable.setValueAt(UtilityFunctions.to64BitHexString(MemoryAccess.MEM_WB_LMD), 13, 1);
        internalRegTable.setValueAt(UtilityFunctions.to64BitHexString(MemoryAccess.MEM_WB_ALU_OUTPUT), 14, 1);
    }

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        pipelinePanel.repaint();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        dialogClass.createDialog("NOINPUT", 0, 0, 1);
        dialogClass.showDialog();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        Scheduler.getInstance().runOneCycle();
        updateTables();
        pipelinePanel.updatePanel(Scheduler.getInstance().getCycles());
        pipelinePanel.repaint();
    }//GEN-LAST:event_jMenu5MouseClicked

    public void jumpToMemory(int cell) {
        memoryTable.scrollRectToVisible(new Rectangle(memoryTable.getCellRect(cell, 0, true)));
    }

    public void setValue(String memoryAddress, String value, int toggle, int row) {
        String s;

        try {
            if (toggle == 0) {
                //register
                DefaultTableModel model = (DefaultTableModel) registerTable.getModel();
                Storage.storeRegisterValue(row, Long.parseUnsignedLong(value, 16));
                s = (UtilityFunctions.to64BitHexString(Storage.getRegisterValue(row))).toUpperCase();
                model.setValueAt(s, row, 1);
            } else {
                //memory
                DefaultTableModel model = (DefaultTableModel) memoryTable.getModel();
                Storage.dataStoreDouble(Integer.parseInt(memoryAddress, 16), Long.parseUnsignedLong(value, 16));
                s = (UtilityFunctions.to64BitHexString(Storage.dataLoadDouble(Integer.parseInt(memoryAddress, 16)))).toUpperCase();
                model.setValueAt(s, row, 1);
            }
        } catch (Exception e) {
            //do nothing
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable codeTable;
    private javax.swing.JTable internalRegTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JMenu loadButton;
    private javax.swing.JTable memoryTable;
    private javax.swing.JTable registerTable;
    private javax.swing.JTextArea sourceCodeArea;
    // End of variables declaration//GEN-END:variables
}
